---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: angular-deployment 
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector: 
    matchLabels: 
      web: angular
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        web: angular 
    spec: 
      containers: 
      - name: angular 
        image: glgelopfalcon/angular-realworld:5
        ports: 
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3  
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1      
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: angular-service 
spec: 
  selector: 
    web: angular
  ports: 
  - port: 80
    targetPort: 80
  type: NodePort 